project:
  type: website
  output-dir: docs

website:
  title: "Tallen Vidal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - projects.qmd
      - text: Dashboards
        href: https://tallenvidal1.github.io/Dashboards/
        target: blank
    right: 
      - icon: github
        href: https://github.com/TallenVidal1
        target: blank
      
format:
  html:
    theme:
      light: pulse
    #  dark: pulse
    css: styles.css
    toc: true

editor: visual

